version: '2.1'

services:
  construmart:
    restart: always
    build: .
    environment:     
    - VIRTUAL_HOST=easy.backend.boldware.cl
    - VIRTUAL_PORT=80 

networks:
   default:
      external:
         name: nginxproxy_nginx-network