# Generated by Django 2.0.6 on 2018-07-13 22:30

from django.db import migrations, models
import face.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_mongo', models.IntegerField(unique=True)),
                ('image1', models.ImageField(upload_to=face.models.person_directory_path_1)),
                ('image2', models.ImageField(upload_to=face.models.person_directory_path_2)),
                ('image3', models.ImageField(upload_to=face.models.person_directory_path_3)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
