# Generated by Django 2.0.6 on 2018-07-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id_mongo',
            field=models.IntegerField(),
        ),
    ]
