# Generated by Django 2.0.6 on 2018-06-15 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person_image',
            old_name='imagen',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='person_image',
            old_name='persona',
            new_name='person',
        ),
    ]
