# Generated by Django 2.0.6 on 2018-07-18 05:35

from django.db import migrations, models
import face.models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0002_auto_20180718_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id_mongo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='image1',
            field=models.ImageField(null=True, upload_to=face.models.person_directory_path_1),
        ),
        migrations.AlterField(
            model_name='person',
            name='image2',
            field=models.ImageField(null=True, upload_to=face.models.person_directory_path_2),
        ),
        migrations.AlterField(
            model_name='person',
            name='image3',
            field=models.ImageField(null=True, upload_to=face.models.person_directory_path_3),
        ),
    ]
