# Generated by Django 2.0.6 on 2018-07-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0003_auto_20180718_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id_mongo',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
