# Generated by Django 2.0.6 on 2018-06-16 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0005_auto_20180616_1142'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person_Image',
            new_name='PersonImage',
        ),
    ]
